from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Tuple


C_TYPE_MAP = {
    "uint8": "uint8_t",
    "uint16": "uint16_t",
    "uint32": "uint32_t",
    "int8": "int8_t",
    "float32": "float",
}


def _sanitise_name(name: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z_]+", "_", name)
    if re.match(r"^[0-9]", name):
        name = "f_" + name
    return name


def _c_struct_name(msg_name: str) -> str:
    return f"{msg_name.upper()}_t"


def generate_c_header(protocol: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("// Auto-generated by SwarmAI Platform Demo")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Header
    lines.append("// Common message header")
    lines.append("#pragma pack(push, 1)")
    lines.append("typedef struct {")
    for f in protocol.get("header_fields", []):
        ctype = C_TYPE_MAP.get(f["type"], "uint8_t")
        fname = _sanitise_name(f["name"])
        lines.append(f"    {ctype} {fname}; // {f.get('desc','')}")
    lines.append("} msg_header_t;")
    lines.append("")

    # Messages
    for msg in protocol.get("messages", []):
        sname = _c_struct_name(msg["name"])
        lines.append(f"// Message: {msg['name']} (id={msg.get('msg_id')})")
        lines.append("typedef struct {")
        lines.append("    msg_header_t hdr;")
        for f in msg.get("fields", []):
            ftype = f["type"]
            fname = _sanitise_name(f["name"])
            if ftype == "struct[]":
                # Variable-length placeholder
                lines.append(f"    // TODO: variable-length array: {fname}")
                lines.append(f"    uint16_t {fname}_len; // number of elements")
                lines.append(f"    uint8_t {fname}_bytes[0]; // flexible array member")
                continue
            ctype = C_TYPE_MAP.get(ftype, "uint8_t")
            lines.append(f"    {ctype} {fname}; // {f.get('desc','')}")
        lines.append(f"}} {sname};")
        lines.append("")

    lines.append("#pragma pack(pop)")
    lines.append("")

    # Encode/decode prototypes (left for integrators)
    lines.append("// TODO: Implement encode/decode per your transport layer")
    lines.append("// size_t encode_<MSG>(uint8_t* out, size_t cap, const <MSG>_t* in);")
    lines.append("// bool decode_<MSG>(<MSG>_t* out, const uint8_t* in, size_t len);")

    return "\n".join(lines)


PY_TYPE_MAP = {
    "uint8": "int",
    "uint16": "int",
    "uint32": "int",
    "int8": "int",
    "float32": "float",
    "struct[]": "bytes",
}


def generate_python_dataclasses(protocol: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("# Auto-generated by SwarmAI Platform Demo")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("from typing import Optional")
    lines.append("")

    # Header
    lines.append("@dataclass")
    lines.append("class MsgHeader:")
    for f in protocol.get("header_fields", []):
        pytype = PY_TYPE_MAP.get(f["type"], "int")
        fname = _sanitise_name(f["name"])
        lines.append(f"    {fname}: {pytype}  # {f.get('desc','')}")
    lines.append("")

    for msg in protocol.get("messages", []):
        cname = "".join([p.capitalize() for p in msg["name"].lower().split("_")])
        lines.append("@dataclass")
        lines.append(f"class {cname}:")
        lines.append("    hdr: MsgHeader")
        for f in msg.get("fields", []):
            pytype = PY_TYPE_MAP.get(f["type"], "int")
            fname = _sanitise_name(f["name"])
            lines.append(f"    {fname}: {pytype}  # {f.get('desc','')}")
        lines.append("")

    lines.append(
        "\n# NOTE: This file only defines data containers. You should implement serialization (CBOR/Protobuf/flatbuffers/custom) separately.\n"
    )
    return "\n".join(lines)


def write_codegen(out_dir: str | Path, protocol: Dict[str, Any]) -> Tuple[Path, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    c_h = out_dir / "messages.h"
    py_f = out_dir / "messages.py"

    c_h.write_text(generate_c_header(protocol), encoding="utf-8")
    py_f.write_text(generate_python_dataclasses(protocol), encoding="utf-8")

    return c_h, py_f
